name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        run: |
          for dir in images/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              image="ghcr.io/tyzbit/containers/$name:latest"
              echo "Building $image"
              docker build -t "$image" "$dir"
              docker push "$image"
            fi
          done
